version: 2

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "08:00"
    timezone: Asia/Jakarta
  open-pull-requests-limit: 100
  groups:
    feathersjs:
      applies-to: version-updates
      patterns:
        - "@feathersjs*"
    development-dependencies:
      dependency-type: "development"
  
- package-ecosystem: npm
  directory: "/infra"
  schedule:
    interval: weekly
    time: "08:00"
    timezone: Asia/Jakarta
  open-pull-requests-limit: 100
  groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
    
 
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "08:00"
    timezone: Asia/Jakarta
  open-pull-requests-limit: 100
  reviewers:
  - berviantoleo
  assignees:
  - berviantoleo

- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "08:00"
    timezone: Asia/Jakarta
  open-pull-requests-limit: 100
  reviewers:
  - berviantoleo
  assignees:
  - berviantoleo
